version: '3'

services:
  homeassistant-garage-door-test:
    container_name: home-assistant
    image: homeassistant/home-assistant
    environment:
      # This is the required way to set a timezone on macOS and differs from the Linux compose file
      - TZ=Australia/Melbourne
    volumes:
      - ./ha_config:/config
    restart: always
    ports:
      # Also required for macOS since the network directive in docker-compose does not work
      - "8123:8123"

# Add this or docker-compose will complain that it did not find the key for locally mapped volume
volumes:
  config: